ignores empty rows
laravel-enso/data-import pull request #22
Opened 2019-07-02 15:35 UTC by vmcvlad

2019-07-02 15:39 UTC, aocneanu commented
omg

2019-07-02 19:09 UTC, vmcvlad commented
> omg

"first make it work, then make it better" :smile:

2019-07-03 05:37 UTC, aocneanu requested changes

2019-07-03 05:37 UTC, aocneanu commented on src/app/Services/Worksheet/Row.php
> +        });
refactor to `return $this->values()->filter()->isNotEmpty()`

2019-07-03 05:37 UTC, aocneanu commented on src/app/Services/Worksheet/Row.php
> +            : false;
equivalent to `return $validCell === null` ...

2019-07-03 05:37 UTC, aocneanu commented on src/app/Services/Importers/Import.php
> +            $currrentRow = $this->row();
rename $currentRow -> $row

2019-07-03 05:37 UTC, aocneanu commented on src/app/Services/Worksheet/Row.php
> +    public function isEmpty()
we need `isNotEmpty()`

2019-07-03 05:37 UTC, aocneanu commented on src/app/Services/Importers/Import.php
> +            if (! $currrentRow->isEmpty()) {
`$row->isNotEmpty()`

2019-07-05 10:38 UTC, merged