Feature/improve jobs
laravel-enso/data-import pull request #54
Opened 2020-11-18 09:19 UTC by raftx24

2020-11-18 16:22 UTC, aocneanu requested changes
With job batching L8 also adds the ability to programatically cancel a batch.

This means that we could use something like
```php
        if ($this->dataImport->status === Statuses::Canceled) {
            $this->batch()->cancel();
        } else {
            (new Chunk(
                $this->dataImport,
                $this->template,
                $this->user,
                $this->params,
                $this->sheetName,
                $this->chunk,
                $this->index
            ))->run();
        }
    }
```

in our ChukImport job

Also we might not need or we may use the same technique in the other places where we were checking for the canceled status

I guess naming the batch something like "importing filename.xlsx" would be good also for horizon

2020-11-18 16:22 UTC, aocneanu commented on src/Services/Importers/Finalize.php
> +        $this->dataImport->refresh()
let's move the refresh in the Import class, when we instantiate Finalize

2020-11-18 16:22 UTC, aocneanu commented on src/Services/Importers/Finalize.php
> +<?php
wrap this service in a job, and dispatch the job in batch->then()

The job will use `SerializesModels` so the dataImport->refresh is not longer needed

2020-11-18 16:22 UTC, aocneanu commented on src/Services/Exporters/Rejected.php
>          $this->hashFilename = $this->hashFilename();
wrap this in a job and run the job in batch->then(). This way the splitting job will not run the export rejected task, and the pipeline won't stay blocked.

2020-11-24 12:54 UTC, raftx24 commented
> With job batching L8 also adds the ability to programatically cancel a batch.
> 
> This means that we could use something like
> 
> ```
>         if ($this->dataImport->status === Statuses::Canceled) {
>             $this->batch()->cancel();
>         } else {
>             (new Chunk(
>                 $this->dataImport,
>                 $this->template,
>                 $this->user,
>                 $this->params,
>                 $this->sheetName,
>                 $this->chunk,
>                 $this->index
>             ))->run();
>         }
>     }
> ```
> 
> in our ChukImport job
> 
> Also we might not need or we may use the same technique in the other places where we were checking for the canceled status
> 
> I guess naming the batch something like "importing filename.xlsx" would be good also for horizon

@aocneanu , I guess we cannot remove other places!  
![image](https://user-images.githubusercontent.com/10864136/100096458-47758b80-2e71-11eb-9e14-8fb7fbd83e36.png)  
this happens before ->batch->cancel()  
![image](https://user-images.githubusercontent.com/10864136/100096531-6411c380-2e71-11eb-931f-860b430c7472.png)    
this happens before ->batch->cancel()

2020-11-25 14:23 UTC, merged